<?php

/**
 * Implementation of hook_menu_alter().
 */
function webform_export_menu_alter(&$items) {
  $items['node/%webform_menu/webform-results/download'] = array(
    'title' => t('Download'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_export_download_form', 1),
    'access callback' => 'user_access',
    'access arguments' => array('access all webform results'),
    'file path' => drupal_get_path('module', 'webform_export'),
    'file' => 'webform_export.inc',
    'type' => MENU_LOCAL_TASK,
  );
}