<?php

/**
 * Implementation of hook_menu().
 */
function webform_export_menu() {
  return array(
    'node/%webform_menu/webform-results/export' => array(
      'title' => t('Export'),
      'page callback' => 'webform_export_export_callback',
      'page arguments' => array(1),
      'access callback' => 'user_access',
      'access arguments' => array('access all webform results'),
      'file' => 'webform_export.inc',
      'type' => MENU_LOCAL_TASK,
    ),
    'node/%webform_menu/webform-results/status' => array(
      'title' => t('Status'),
      'page callback' => 'webform_export_status_callback',
      'page arguments' => array(1),
      'access callback' => 'user_access',
      'access arguments' => array('access all webform results'),
      'file' => 'webform_export.inc',
      'type' => MENU_LOCAL_TASK,
    ),
  );
}

/**
 * Implementation of hook_theme().
 */
function webform_export_theme() {
  return array(
    'webform_export_status' => array('arguments' => array('node' => NULL), 'template' => 'webform_export-status', 'file' => 'webform_export.theme.inc'),
  );
}

/**
 * Implementation of hook_action_info().
 */
function webform_export_action_info() {
  return array(
    'webform_export_export_action' => array(
      'type' => 'node',
      'description' => t('Export webform submissions.'),
      'configurable' => FALSE,
      'hooks' => array(
        'nodeapi' => array('presave'),
      ),
    ),
  );
}

/**
 * Implementation of a Drupal action.
 * Export webform submissions.
 */
function webform_export_export_action(&$node, $context = array()) {
  watchdog('action', 'Export %title submissions.', array('%title' => $node->title));
}
